"""add user preferences

Revision ID: 171e97815682
Revises: a9431d855cdb
Create Date: 2025-10-19 17:41:47.454832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171e97815682'
down_revision: Union[str, Sequence[str], None] = 'a9431d855cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cards_per_session', sa.Integer(), nullable=False, server_default='20'))
        batch_op.add_column(sa.Column('review_order', sa.String(), nullable=False, server_default='random'))
        batch_op.add_column(sa.Column('show_examples', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=False, server_default='light'))
        batch_op.add_column(sa.Column('daily_goal', sa.Integer(), nullable=False, server_default='50'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_goal')
        batch_op.drop_column('theme')
        batch_op.drop_column('show_examples')
        batch_op.drop_column('review_order')
        batch_op.drop_column('cards_per_session')

    # ### end Alembic commands ###
