"""add indexes

Revision ID: 2cce485038cf
Revises: bdf2fb74b5b8
Create Date: 2025-11-01 18:51:34.035325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cce485038cf'
down_revision: Union[str, Sequence[str], None] = 'bdf2fb74b5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('leitnerstate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leitnerstate_flashcard_id'), ['flashcard_id'], unique=True)

    with op.batch_alter_table('reviewhistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewhistory_flashcard_id'), ['flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviewhistory_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_token'), ['session_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_token'))

    with op.batch_alter_table('reviewhistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewhistory_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviewhistory_flashcard_id'))

    with op.batch_alter_table('leitnerstate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leitnerstate_flashcard_id'))

    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_user_id'))
        batch_op.drop_index(batch_op.f('ix_flashcard_topic_id'))

    # ### end Alembic commands ###
