"""add auth fields and answer_mode

Revision ID: bdf2fb74b5b8
Revises: 171e97815682
Create Date: 2025-10-22 19:49:56.262868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf2fb74b5b8'
down_revision: Union[str, Sequence[str], None] = '171e97815682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('session_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('answer_mode', sa.String(), nullable=False, server_default='reveal'))
        batch_op.create_index('ix_user_session_token', ['session_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_session_token')
        batch_op.drop_column('answer_mode')
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('token_expires')
        batch_op.drop_column('session_token')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
